### ISSUE TITLE
18 Compiler Warnings

### ISSUE THREAD

**Issue by ogezue** [DigitalExpansion/AppPermissions#3]
Is it possible to remove the compiler warnings for iOS9 projects?

![bildschirmfoto 2016-02-19 um 10 56 48](https://cloud.githubusercontent.com/assets/2361031/13172355/f43bf830-d6f7-11e5-9951-dc85ffc0d380.png)

**Comment by sanchosrancho** [comment]
The problem is that these checks need to be included in the project to get everything to compile with a deployment target of iOS 7.0. When you use pods with a deployment target of 9.0, the availability methods will show the warning. That's could be annoying.

The simple way to avoid warnings third-party libraries is to set `Inhibit All Warnings` setting to `YES` in Pods target:
![image](https://cloud.githubusercontent.com/assets/833941/13173588/6bc84662-d70f-11e5-93a0-38ec85d7bc4a.png)

**Comment by ogezue** [comment]
thanks for that hint! perhaps you can find a solution in nickoneill/PermissionScope. The offer the same with less warnings
